name: output information
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
